In [3]:
from generatorUtils import LabelTransformations
import random
from faker import Faker
f = Faker()
from collections import Counter

In [4]:
loan_labels = ['loan', 'loan amount', 'credit amount']
transaction_labels = ['transaction amount', 'transaction', 'bid', 'bid amount', 'balance']
income_labels = ['salary', 'salary amount', 'income', 'income amount']

labels = loan_labels + transaction_labels + income_labels

In [23]:
class AmountGenerator:
    def __init__(self, num_of_samples):
        self.labelTransformations = LabelTransformations()
        self.num_of_samples = num_of_samples
        self.f = Faker()

    def get_currency_abbreviation(self,):
        return ' ' + f.currency_code()

    def get_currency_symbol(self,):
        return ' ' + f.currency_symbol()

    def get_currency_name(self,):
        return ' ' + f.currency_name()

    def amount_transform(self, input_amount, output_amount):

        input_amount_with_commas = f"{int(input_amount):,}" 
        output_amount_with_commas = f"{int(output_amount):,}" 


        input_pnumber = input_amount_with_commas.split(',')[0]
        output_pnumber = output_amount_with_commas.split(',')[0]

        input_fraction_pnumber = str(eval(input_pnumber) + eval("{:.2f}".format(random.random())))
        output_fraction_pnumber = str(eval(output_pnumber) + eval("{:.2f}".format(random.random())))


        input_comma_count = Counter(input_amount_with_commas)
        input_comma_count = input_comma_count[',']
        output_comma_count = Counter(output_amount_with_commas)
        output_comma_count = output_comma_count[',']

        if input_comma_count == 1:
            input_unit= random.choice(['k', 'thousand', ' k', ' thousand'])
        elif input_comma_count == 2:
            input_unit= random.choice(['mn', 'million', ' mn', ' million'])
        elif input_comma_count == 3:
            input_unit= random.choice(['bn', 'billion', ' bn', ' billion'])
        else:
            input_unit = ''

        # if output_comma_count == 1:
        #     output_unit= random.choice(['k', 'thousand', ' k', ' thousand'])
        # elif output_comma_count == 2:
        #     output_unit= random.choice(['mn', 'million', ' mn', ' million'])
        # elif output_comma_count == 3:
        #     output_unit= random.choice(['bn', 'billion', ' bn', ' billion'])
        # else:
        #     output_unit = ''
        output_unit = input_unit

        return [input_amount, input_amount+"{:.2f}".format(random.random()), input_amount_with_commas, input_amount_with_commas+"{:.2f}".format(random.random()), input_pnumber + input_unit, input_fraction_pnumber + input_unit],\
                [output_amount, output_amount+"{:.2f}".format(random.random()), output_amount_with_commas, output_amount_with_commas+"{:.2f}".format(random.random()), output_pnumber + output_unit, output_fraction_pnumber + output_unit]

        
    def generateAmountData(self, labels):
        labels = list(set(self.labelTransformations(labels)))
        
        input_amount_list = []
        output_amount_list = []
        for i in range(self.num_of_samples):
            

            '''amounts of length 4 to 10'''
            input_amount_list, output_amount_list = self.generateAmount(labels, input_amount_list, output_amount_list, 4)
            input_amount_list, output_amount_list = self.generateAmount(labels, input_amount_list, output_amount_list, 5)
            input_amount_list, output_amount_list = self.generateAmount(labels, input_amount_list, output_amount_list, 6)
            input_amount_list, output_amount_list = self.generateAmount(labels, input_amount_list, output_amount_list, 7)
            input_amount_list, output_amount_list = self.generateAmount(labels, input_amount_list, output_amount_list, 8)
            input_amount_list, output_amount_list = self.generateAmount(labels, input_amount_list, output_amount_list, 9)
            input_amount_list, output_amount_list = self.generateAmount(labels, input_amount_list, output_amount_list, 10)

        return input_amount_list, output_amount_list
        
    def generateAmount(self, labels, input_amount_list, output_amount_list, length):
        
        #without currencies
        start_number = str(random.randint(a=0, b=9))
        label = random.choice(labels)
        input_following_random_number = self.generate_random_number(length-1)
        output_following_random_number = self.generate_random_number(length-1)

        input_amount = start_number + input_following_random_number
        output_amount = start_number + output_following_random_number

        input_amount_transforms, output_amount_transforms = self.amount_transform(input_amount, output_amount)
        random_index = random.choice(list(range(len(input_amount_transforms))))
        input_amount_list.append(label + ': ' + input_amount_transforms[random_index])
        output_amount_list.append(output_amount_transforms[random_index])

        #with currency symbol
        start_number = str(random.randint(a=0, b=9))
        label = random.choice(labels)
        currency_symbol = self.get_currency_symbol()
        
        input_following_random_number = self.generate_random_number(length-1)
        output_following_random_number = self.generate_random_number(length-1)

        input_amount = start_number + input_following_random_number
        output_amount = start_number + output_following_random_number

        input_amount_transforms, output_amount_transforms = self.amount_transform(input_amount, output_amount)
        random_index = random.choice(list(range(len(input_amount_transforms))))
        input_amount_list.append(label + ': ' + input_amount_transforms[random_index] + currency_symbol)
        output_amount_list.append(output_amount_transforms[random_index] + currency_symbol)

        #with currency abbreviation
        start_number = str(random.randint(a=0, b=9))
        label = random.choice(labels)
        currency_abbreviation = self.get_currency_abbreviation()
        input_following_random_number = self.generate_random_number(length-1)
        output_following_random_number = self.generate_random_number(length-1)

        input_amount = start_number + input_following_random_number
        output_amount = start_number + output_following_random_number

        input_amount_transforms, output_amount_transforms = self.amount_transform(input_amount, output_amount)
        random_index = random.choice(list(range(len(input_amount_transforms))))
        input_amount_list.append(label + ': ' + input_amount_transforms[random_index] + currency_abbreviation)
        output_amount_list.append(output_amount_transforms[random_index] + currency_abbreviation)

        #with currency name
        start_number = str(random.randint(a=0, b=9))
        label = random.choice(labels)
        currency_name = self.get_currency_name()
        input_following_random_number = self.generate_random_number(length-1)
        output_following_random_number = self.generate_random_number(length-1)

        input_amount = start_number + input_following_random_number
        output_amount = start_number + output_following_random_number

        input_amount_transforms, output_amount_transforms = self.amount_transform(input_amount, output_amount)
        random_index = random.choice(list(range(len(input_amount_transforms))))
        input_amount_list.append(label + ': ' + input_amount_transforms[random_index] + currency_name)
        output_amount_list.append(output_amount_transforms[random_index] + currency_name)

        return input_amount_list, output_amount_list
            
            

    def generate_random_number(self, length):
        start = eval(''.join(['1'] + ['0' for i in range(1, length-1)]))
        end = eval(''.join(['9' for i in range(1, length)]))

        start = int(eval('1' + str(start)))
        end = int(eval('9' + str(end)))


        random_number = str(random.randint(a=start, b=end))
        return random_number

In [24]:
amountGenerator = AmountGenerator(num_of_samples = 600)

In [25]:
input, output = amountGenerator.generateAmountData(labels)

In [26]:
import pandas as pd
res = pd.DataFrame(columns=['input_entity', 'output_entity'])

In [27]:
res['input_entity'] = input
res['output_entity'] = output

In [28]:
len(res)

16800

In [29]:
res.to_csv('Amount_data.csv', index=False)

In [30]:
res

,input_entity,output_entity
0,salary amount: 8.72 k,8.55 k
1,"INCOME AMOUNT: 3,6460.12 ₨","3,7850.56 ₨"
2,"LoanAmount: 1,6800.64 IRR","1,1140.12 IRR"
3,CreditAmount: 4673 Japanese yen,4875 Japanese yen
4,incomeAmount: 47275,42226
...,...,...
16795,Loan-Amount: 041954643 Turkish lira,033643187 Turkish lira
16796,incomeAmount: 6346170254,6964051522
16797,balance: 3 bn ¥,3 bn ¥
16798,CREDIT_AMOUNT: 9.58billion PAB,9.38billion PAB
16799,loanAmount: 42574303230.96 Solomon Islands dollar,47687847250.17 Solomon Islands dollar

In [31]:
res[:100]

,input_entity,output_entity
0,salary amount: 8.72 k,8.55 k
1,"INCOME AMOUNT: 3,6460.12 ₨","3,7850.56 ₨"
2,"LoanAmount: 1,6800.64 IRR","1,1140.12 IRR"
3,CreditAmount: 4673 Japanese yen,4875 Japanese yen
4,incomeAmount: 47275,42226
...,...,...
95,"TRANSACTION-AMOUNT: 559,7850.18 Bahamian dollar","533,9750.52 Bahamian dollar"
96,"Transaction-Amount: 8,553,277","8,165,957"
97,CREDIT-AMOUNT: 8323034 ﷼,8796706 ﷼
98,"income-amount: 324,754 GBP","752,546 GBP"
99,"SALARYAMOUNT: 7,337,3950.96 Renminbi","7,405,3410.19 Renminbi"